language: ruby

cache: bundler

rvm:
  - 2.6
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - 3.3

script:
  - bundle exec rake spec
  - bundle exec bin/gemplate --help

before_script:
  - gem update --system
  - gem install bundler
